<form method="get" class="form-horizontal">
	<div class="modal fade" tabindex="-1" role="dialog" id="auth-search">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"
						aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<h4 class="modal-title">
						<i class="fa fa-user" aria-hidden="true"></i>
					<?php echo $this->translate('Auth Search'); ?></h4>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label for="authName" class="col-sm-2 control-label"><?php echo $this->translate("Name")?></label>
						<div class="col-sm-10">
							<input type="text" class="form-control" id="authName" name="authName" value="<?php echo $this->queryParams["authName"]; ?>">
						</div>
					</div>
				
					<div class="form-group">
						<label for="authEmail" class="col-sm-2 control-label"><?php echo $this->translate("E-Mail")?></label>
						<div class="col-sm-10">
							<input type="text" class="form-control" id="authEmail" name="authEmail" value="<?php echo $this->queryParams["authEmail"]; ?>">
						</div>
					</div>
					
					<div class="form-group">
						<label for="aclRoleId" class="col-sm-2 control-label"><?php echo $this->translate('Location'); ?>:</label>
						<div class="col-sm-10">
							<select class="form-control" name="aclRoleId" id="aclRoleId">
								<option value=""><?php echo $this->translate('Select'); ?></option>
								<?php foreach($this->roleEntitys as $entity): ?>
								<option value="<?php echo $entity->getAclRoleId(); ?>" <?php if($this->queryParams['aclRoleId'] == $entity->getAclRoleId()): ?>selected<?php endif; ?>>
									<?php echo ucwords($entity->getAclRoleName()); ?>
								</option>
								<?php endforeach; ?>
							</select>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
					<button type="submit" class="btn btn-primary"><?php echo $this->translate('Search'); ?></button>
				</div>
			</div>
		</div>
	</div>
</form>