<?php
/**
* Pacific NM (https://www.pacificnm.com)
*
* @link      https://github.com/pacificnm/pnm for the canonical source repository
* @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
* @license
*/
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="fa fa-cog"></i>
					<?php echo $this->translate('Auth'); ?>
				</h3>
				<div class="box-tools">
					<?php echo $this->createButton('auth-create'); ?>
				</div>
			</div>
			<?php if($this->paginator->count() == 0): ?>
			<div class="box-body">
				<div class="alert alert-info">
					<p>
						<i class="fa fa-info-circle" aria-hidden="true"></i>
					</p>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body no-padding">
				<div class="table-responsive">
    				<table class="table table-hover">
    					<thead>
    						<tr>
    							<th><?php echo $this->translate('E-Mail');?></th>
    							<th><?php echo $this->translate('Name');?></th>
    							<th><?php echo $this->translate('Role');?></th>
    							<th><?php echo $this->translate('Last Sign In');?></th>
    						</tr>
    					</thead>
    					<tbody>
    					<?php foreach($this->paginator as $authEntity): ?>
    						<tr>
    							<td><a href="<?php echo $this->url('auth-view', array('id' => $authEntity->getAuthId())); ?>" title="<?php echo $this->translate('View this auth'); ?>"><?php echo $authEntity->getAuthEmail(); ?></a></td>
    							<td><?php echo $authEntity->getAuthName(); ?></td>
    							<td><?php echo ucwords($authEntity->getAclRoleEntity()->getAclRoleName()); ?></td>
    							<td><?php echo ($authEntity->getAuthLastLogin() > 0) ? date($this->appConfig()->getConfigDateLong(), $authEntity->getAuthLastLogin()) : $this->translate('Never Signed In'); ?></td>
    							
    						</tr>
    					<?php endforeach; ?>
    					</tbody>
    				</table>
				</div>
				<div class="row">
					<div class="col-xs-12 text-center">
						<?php echo $this->Paginator(
							$this->itemCountPerPage, 
							$this->itemCount, 
							$this->pageCount, 
                            $this->page, 
                            $this->routeParams,
                            $this->queryParams);
                        ?>
					</div>
				</div>
			</div>
			<?php endif; ?>
		</div>
	</div>
</div>