<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
					<?php echo $this->translate("Edit Auth"); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<?php echo $this->form()->openTag($this->form); ?>
				
				<?php echo $this->partial("partials/form-errors.phtml", array("errorMsg" => $this->form->getMessages())); ?>
				
				<div class="row">
              		<div class="col-xs-12">
              			<?php echo $this->formElementDisplay($this->form->get("authEmail")); ?>
					</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12">
              			<?php echo $this->formElementDisplay($this->form->get("authName")); ?>
					</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12">
              			<?php echo $this->formElementDisplay($this->form->get("authPassword")); ?>
					</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12">
              			<?php echo $this->formElementDisplay($this->form->get("aclRoleId")); ?>
					</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12">
              			<?php echo $this->formElementDisplay($this->form->get("submit")); ?>
              		</div>
              	</div>
				
				<?php echo $this->formElementDisplay($this->form->get("authId")); ?>
				
				<?php echo $this->formElementDisplay($this->form->get("authLastLogin")); ?>
				
				<?php echo $this->formElementDisplay($this->form->get("authLastIp")); ?>
				
				<?php echo $this->form()->closeTag(); ?>
			</div>
		</div>
	</div>
</div>