<div class="row">
	<div class="col-md-3">
		<!-- Profile Image -->
		<div class="box box-primary">
			<div class="box-body box-profile">
				<img class="profile-user-img img-responsive img-circle"
					src="../../dist/img/user4-128x128.jpg" alt="User profile picture">

				<h3 class="profile-username text-center"><?php echo $this->entity->getAuthName(); ?></h3>

				<p class="text-muted text-center"><?php echo ucwords($this->entity->getAclRoleEntity()->getAclRoleName()); ?></p>

				<ul class="list-group list-group-unbordered">
					<li class="list-group-item"><b><?php echo $this->translate("E-Mail"); ?>:</b> 
						<a class="pull-right"><?php echo $this->entity->getAuthEmail(); ?></a>
					</li>
					<li class="list-group-item"><b><?php echo $this->translate("Last Sign In"); ?>:</b> 
						<a class="pull-right"><?php echo date($this->appConfig()->getConfigDateLong(), $this->entity->getAuthLastLogin()); ?></a>
					</li>
					<li class="list-group-item"><b><?php echo $this->translate("Last IP Address"); ?>:</b> 
						<a class="pull-right"><?php echo $this->entity->getAuthLastIp();?></a>
					</li>
				</ul>
			</div>
		</div>
	</div>

	<div class="col-md-9">
		<div class="nav-tabs-custom">
			<ul class="nav nav-tabs">
				<li>
					<a href="<?php echo $this->url("auth-profile-index"); ?>" title="<?php echo $this->translate("Activity"); ?>">
						<i class="fa fa-history"></i> <?php echo $this->translate("Activity"); ?>
					</a>
				</li>
				<li  class="active">
					<a href="<?php echo $this->url("auth-profile-update"); ?>" title="<?php echo $this->translate("Settings"); ?>">
						<i class="fa fa-gear"></i> <?php echo $this->translate("Settings"); ?>
					</a>
				</li>
				<li><a href="<?php echo $this->url("auth-profile-password"); ?>" title="<?php echo $this->translate("Password")?>">
						<i class="fa fa-lock"></i> <?php echo $this->translate("Password"); ?>
					</a>
				</li>
			</ul>
			<div class="tab-content">
				<div class="tab-pane" id="activity"></div>
				<div class="active tab-pane" id="settings">
				
					<?php echo $this->form()->openTag($this->form); ?>
				<?php echo $this->partial("partials/form-errors.phtml", array("errorMsg" => $this->form->getMessages())); ?>
				
				<div class="row">
              		<div class="col-xs-12">
						<?php $element = $this->form->get("authName"); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12">
						<?php $element = $this->form->get("authEmail"); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	
				<?php echo $this->formElement($this->form->get("authId")); ?>
				<?php echo $this->formElement($this->form->get("aclRoleId")); ?>
				<?php echo $this->formElement($this->form->get("authPassword")); ?>
				<?php echo $this->formElement($this->form->get("authLastLogin")); ?>
				<?php echo $this->formElement($this->form->get("authLastIp")); ?>
				<?php echo $this->formSubmit($this->form->get("submit")); ?>
				<?php echo $this->form()->closeTag(); ?>
				</div>
			</div>
		</div>
	</div>
</div>