<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
					<?php echo $this->translate('View Auth'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('auth-password', array('id' => $this->entity->getAuthId())); ?>" 
						title="<?php echo $this->translate('Reset Password'); ?>" class="btn btn-box-tool">
						<i class="fa fa-lock"></i> <?php echo $this->translate('Password'); ?>
					</a>
					<?php echo $this->deleteButton('auth-delete', array('id' => $this->entity->getAuthId()));?>
					
					<?php echo $this->updateButton('auth-update', array('id' => $this->entity->getAuthId())); ?>
				</div>
			</div>
			<div class="box-body box-profile">
				 <h3 class="profile-username"><?php echo $this->entity->getAuthName(); ?></h3>
				 <p class="text-muted"><?php echo $this->entity->getAuthEmail(); ?></p>
				 <ul class="list-group list-group-unbordered">
				 	<li class="list-group-item">
				 		<b><?php echo $this->translate('Role');?>:</b> 
				 		<?php echo $this->entity->getAclRoleEntity()->getAclRoleName(); ?>
				 	</li>
 				 	<li class="list-group-item">
 				 		<b><?php echo $this->translate('Last Sign In'); ?>:</b> 
 				 		<?php echo ($this->entity->getAuthLastLogin() > 0) ? date($this->appConfig()->getConfigDateLong(), $this->entity->getAuthLastLogin()) : $this->translate('Never Signed In'); ?>
 				 	</li>
 				 	<li class="list-group-item">
 				 		<b><?php echo $this->translate('Ip Address');?>:</b> 
 				 		<?php echo ($this->entity->getAuthLastIp() != null) ? $this->entity->getAuthLastIp() : $this->translate('Never Signed In'); ?>
 				 	</li>
				 </ul>
			</div>
		</div>
	</div>
</div>

