<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->appConfig()->getConfigCompanyNameShort())->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

		<!-- Disable tap highlight on IE -->
        <meta name="msapplication-tap-highlight" content="no">
    
        <!-- Web Application Manifest -->
        <link rel="manifest" href="manifest.json">
    
        <!-- Add to homescreen for Chrome on Android -->
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="application-name" content="Pacific NM">
        <link rel="icon" sizes="192x192" href="img/chrome-touch-icon-192x192.png">
    
        <!-- Add to homescreen for Safari on iOS -->
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="apple-mobile-web-app-title" content="Pacific NM">
        <link rel="apple-touch-icon" href="img/apple-touch-icon.png">
    
        <!-- Tile icon for Win8 (144x144 + tile color) -->
        <meta name="msapplication-TileImage" content="img/ms-touch-icon-144x144-precomposed.png">
        <meta name="msapplication-TileColor" content="#2F3BA2">
    
        <!-- Color the status bar on mobile devices -->
        <meta name="theme-color" content="#2F3BA2">
		

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('plugins/datatables/dataTables.bootstrap.css'))
            ->prependStylesheet($this->basePath('dist/css/skins/_all-skins.min.css'))
            ->prependStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
            ->prependStylesheet($this->basePath('plugins/timepicker/bootstrap-timepicker.min.css'))
            ->prependStylesheet($this->basePath('plugins/daterangepicker/daterangepicker-bs3.css'))
            ->prependStylesheet($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.css'))
            ->prependStylesheet($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'))
            ->prependStylesheet($this->basePath('font-awesome-4.6.3/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('bootstrap/css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('plugins/datatables/dataTables.bootstrap.min.js'))
            ->prependFile($this->basePath('plugins/datatables/jquery.dataTables.min.js'))
            ->prependFile($this->basePath('plugins/jsignature/jSignature.min.js'))
            ->prependFile($this->basePath('plugins/jquery-idletimer/dist/idle-timer.min.js'))
            ->prependFile($this->basePath('plugins/handelbars/handlebars-v4.0.5.js'))
            ->prependFile($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'))
            ->prependFile($this->basePath('plugins/daterangepicker/daterangepicker.js'))
            ->prependFile($this->basePath('plugins/datepicker/bootstrap-datepicker.js'))
            ->prependFile($this->basePath('plugins/chartjs/Chart.min.js'))
            ->prependFile($this->basePath('plugins/slimScroll/jquery.slimscroll.min.js'))
            ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-world-mill-en.js'))
            ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'))
            ->prependFile($this->basePath('plugins/sparkline/jquery.sparkline.min.js'))
            ->prependFile($this->basePath('/js/moment.js'))
            ->prependFile($this->basePath('dist/js/app.min.js'))
            ->prependFile($this->basePath('plugins/fastclick/fastclick.js'))
            ->prependFile($this->basePath('bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('plugins/jQuery/jQuery-2.2.0.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body class="hold-transition skin-blue sidebar-mini">

		<div class="wrapper">
		
			<header class="main-header">
				<!-- Logo -->
				<a href="<?php echo $this->url('home'); ?>" class="logo">
	                <!-- mini logo for sidebar mini 50x50 pixels -->
					<span class="logo-mini"><b><?php echo $this->appConfig()->getConfigCompanyNameAbv(); ?></b></span>
                    <!-- logo for regular state and mobile devices -->
      				<span class="logo-lg"><b><?php echo $this->appConfig()->getConfigCompanyNameShort(); ?></b></span>
    			</a>
    			
    			<!-- Header Navbar: style can be found in header.less -->
				<nav class="navbar navbar-static-top">
					<!-- Sidebar toggle button-->
					<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
						<span class="sr-only"><?php echo $this->translate('Toggle navigation'); ?></span>
					</a>
					
					<?php echo $this->menuHelper("Top"); ?>
					<!-- Navbar Right Menu -->
					<div class="navbar-custom-menu">
						<ul class="nav navbar-nav">
							<!-- Auth Nav Bar: style can be found in dropdown.less -->
							<?php echo $this->AuthNavBar(); ?>
							<li>
								<a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
							</li>
						</ul>
					</div>
				</nav>
			</header>
			
			<!-- Left side column. contains the logo and sidebar -->
  			<aside class="main-sidebar">
  				<!-- sidebar: style can be found in sidebar.less -->
  				<section class="sidebar">
  					<!-- sidebar menu: : style can be found in sidebar.less -->
  					<ul class="sidebar-menu">
  						<?php echo $this->menuHelper("Left"); ?>
  					</ul>
  				</section>
  			</aside>
  			
  			<!-- Content Wrapper. Contains page content -->
  			<div class="content-wrapper">
  				<section class="content-header">
  					<h1><?php echo $this->pageTitle; ?> <small><?php echo $this->pageSubTitle;?></small></h1>
  					<?php echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial('partials/breadcrumbs'); ?>
  				</section>
  				
  				<section class="content">
  					<?php
                        $flash = $this->flashMessenger();
                        $flash->setMessageOpenFormat('<div%s>
                         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                             &times;
                         </button><p>')
                         ->setMessageSeparatorString('<br />')
                         ->setMessageCloseString('</p></div>');
    
                        echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                        echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                        echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                        echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                    ?>
        			<?php echo $this->content; ?>
        		</section>
        	</div>
        	
            <footer class="main-footer">
            	<div class="pull-right hidden-xs">
            		<b><?php echo $this->translate('Version'); ?></b> <?php echo $this->appConfig()->getConfigVersion();?>
            	</div>
            	<strong><?php echo $this->translate('Copyright'); ?> &copy; <?php echo $this->appConfig()->getConfigCopyYear(); ?>-<?php echo date("Y"); ?> <a href="http://<?php echo $this->appConfig()->getConfigHttpAddress(); ?>"><?php echo $this->appConfig()->getConfigCompanyName(); ?></a>.</strong> <?php echo $this->translate('All rights reserved'); ?>.
            </footer>
            
            <!-- Control Sidebar -->
  			<aside class="control-sidebar control-sidebar-dark">
  				<!-- Create the tabs -->
				<ul class="nav nav-tabs nav-justified control-sidebar-tabs">
					<li><a href="#control-sidebar-favorite-tab" data-toggle="tab"><i class="fa fa-star"></i></a></li>
					<li><a href="#control-sidebar-history-tab" data-toggle="tab"><i class="fa fa-history"></i></a></li>
				</ul>
				<!-- Tab panes -->
				<div class="tab-content">
					
				</div>
  			</aside>
  			 <div class="control-sidebar-bg"></div>  			 
        </div>      

        <?php echo $this->inlineScript() ?>

    </body>
</html>
