<p class="login-box-msg"><?php echo $this->translate('Reset Password');?></p>

<?php echo $this->form()->openTag($this->form); ?>

<div class="alert alert-info">
	<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('Provide the e-mail address you used when you registered your account and we will send further instructions')?>
</div>

<div class="row">
	<div class="col-xs-12">
		<?php $element = $this->form->get('authEmail'); ?>
		<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
			<label class="control-label"><?php echo $element->getLabel() ?></label>
			<?php echo $this->formElement($element); ?>
			<?php if($this->formElementErrors($element)): ?>
				<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
			<?php endif; ?>
		</div>
	</div>
</div>

<?php echo $this->formSubmit($this->form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>

<hr />

<p class="login-box-msg">
	<a href="<?php echo $this->url('auth-sign-in');?>" title="<?php echo $this->translate('Sign in'); ?>"><?php echo $this->translate('Sign in'); ?></a>
</p>