<p class="login-box-msg"><?php echo $this->translate("Reset Password");?></p>

<?php echo $this->form()->openTag($this->form); ?>

<div class="alert alert-info">
	<p><i class="fa fa-info-circle"></i> <?php echo $this->translate("Provide the e-mail address you used when you registered your account and we will send further instructions")?>
</div>

<div class="row">
	<div class="col-xs-12">
		<?php echo $this->formElementDisplay($this->form->get("authEmail")); ?>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<?php echo $this->formElementDisplay($this->form->get("submit")); ?>
	</div>
</div>

<?php echo $this->form()->closeTag(); ?>

<hr />

<p class="login-box-msg">
	<a href="<?php echo $this->url("auth-sign-in");?>" title="<?php echo $this->translate("Sign in"); ?>"><?php echo $this->translate("Sign in"); ?></a>
</p>