<p class="login-box-msg"><?php echo $this->translate("Register Account");?></p>

<?php echo $this->form()->openTag($this->form); ?>

<div class="row">
	<div class="col-xs-12">
		<?php echo $this->formElementDisplay($this->form->get("authEmail")); ?>
	</div>
</div>
 
 <div class="row">
	<div class="col-xs-12">
		<?php echo $this->formElementDisplay($this->form->get("authName")); ?>
 	</div>
</div>
		
<div class="row">
	<div class="col-xs-12">
		<?php echo $this->formElementDisplay($this->form->get("authPassword")); ?>
	</div>
</div>
 	
<div class="row">
	<div class="col-xs-12">
		<?php echo $this->formElementDisplay($this->form->get("confirmPassword")); ?>
	</div>
</div>
 
<div class="row">
	<div class="col-xs-12">
		<?php echo $this->formElementDisplay($this->form->get("submit")); ?>
	</div>
</div> 
 
<?php echo $this->formElementDisplay($this->form->get("authId")); ?>	

<?php echo $this->formElementDisplay($this->form->get("authLastLogin")); ?>	

<?php echo $this->formElementDisplay($this->form->get("authLastIp")); ?>	

<?php echo $this->formElementDisplay($this->form->get("aclRoleId")); ?>	

<?php echo $this->form()->closeTag(); ?>

<br />

<p class="login-box-msg">
	<a href="<?php echo $this->url("auth-sign-in");?>" 
		title="<?php echo $this->translate("Sign in"); ?>">
		<?php echo $this->translate("Sign in"); ?>
	</a>
</p>